### ISSUE TITLE
Building v0.4.2 fails with panick

### ISSUE THREAD

**Issue by amani1104** [AndrewWestberg/cncli#11]
cargo install --path . --force --debug

  ```
Compiling cardano_ouroboros_network v0.0.1-dev (https://github.com/AndrewWestberg/rust-cardano-ouroboros-network?rev=e54237c#e54237c7)
error: failed to compile `cncli v0.4.2 (/root/cncli)`, intermediate artifacts can be found at `/root/cncli/target`

Caused by:
  failed to run custom build command for `cncli v0.4.2 (/root/cncli)`

Caused by:
  process didn't exit successfully: `/root/cncli/target/debug/build/cncli-ba620670c637b420/build-script-build` (exit code: 101)
  --- stdout
  cncli/build.rs:44: Executing "git" "submodule" "update" "--init" "--recursive"
  cncli/build.rs:48: Command "git" "submodule" "update" "--init" "--recursive" finished successfully
  cncli/build.rs:44: Executing "git" "checkout" "66f017f1"
  cncli/build.rs:48: Command "git" "checkout" "66f017f1" finished successfully
  cncli/build.rs:44: Executing "git" "reset" "--hard" "HEAD"
  HEAD is now at 66f017f1 Fix issue when building VRF tests with g++
  cncli/build.rs:48: Command "git" "reset" "--hard" "HEAD" finished successfully
  cncli/build.rs:44: Executing "./autogen.sh"
  libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'build-aux'.
  libtoolize: copying file 'build-aux/ltmain.sh'
  libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
  libtoolize: copying file 'm4/libtool.m4'
  libtoolize: copying file 'm4/ltoptions.m4'
  libtoolize: copying file 'm4/ltsugar.m4'
  libtoolize: copying file 'm4/ltversion.m4'
  libtoolize: copying file 'm4/lt~obsolete.m4'
  Downloading config.guess and config.sub...
  Done.
  cncli/build.rs:48: Command "./autogen.sh" finished successfully
  cncli/build.rs:44: Executing "./configure"

  --- stderr
  HEAD is now at 66f017f1 Fix issue when building VRF tests with g++
  autoreconf: Entering directory `.'
  autoreconf: configure.ac: not using Gettext
  autoreconf: running: aclocal --force -I m4
  autoreconf: configure.ac: tracing
  autoreconf: running: libtoolize --copy --force
  autoreconf: running: /usr/bin/autoconf --force
  autoreconf: configure.ac: not using Autoheader
  autoreconf: running: automake --add-missing --copy --force-missing
  configure.ac:75: installing 'build-aux/compile'
  configure.ac:10: installing 'build-aux/missing'
  src/libsodium/Makefile.am: installing 'build-aux/depcomp'
  autoreconf: Leaving directory `.'
  configure: error: cannot run /bin/bash build-aux/config.sub
  thread 'main' panicked at 'failed to execute "./configure"', build.rs:46:9
  stack backtrace:
     0:     0x564511520ef0 - std::backtrace_rs::backtrace::libunwind::trace::h72c2fb8038f1bbee
                                 at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/../../backtrace/src/backtrace/libunwind.rs:96
     1:     0x564511520ef0 - std::backtrace_rs::backtrace::trace_unsynchronized::h1e3b084883f1e78c
                                 at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/../../backtrace/src/backtrace/mod.rs:66
     2:     0x564511520ef0 - std::sys_common::backtrace::_print_fmt::h3bf6a7ebf7f0394a
                                 at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:79
     3:     0x564511520ef0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h2e8cb764b7fe02e7
                                 at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:58
     4:     0x56451153d70c - core::fmt::write::h7a1184eaee6a8644
                                 at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/fmt/mod.rs:1080
     5:     0x56451151ef62 - std::io::Write::write_fmt::haeeb374d93a67eac
                                 at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/io/mod.rs:1516
     6:     0x56451152301d - std::sys_common::backtrace::_print::h1d14a7f6ad632dc8
                                 at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:61
     7:     0x56451152301d - std::sys_common::backtrace::print::h301abac8bb2e3e81
                                 at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:48
     8:     0x56451152301d - std::panicking::default_hook::{{closure}}::hde0cb80358a6920a
                                 at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:208
     9:     0x564511522cc8 - std::panicking::default_hook::h9b1a691049a0ec8f
                                 at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:227
    10:     0x5645115236a1 - std::panicking::rust_panic_with_hook::h2bdec87b60580584
                                 at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:577
    11:     0x564511523249 - std::panicking::begin_panic_handler::{{closure}}::h101ca09d9df5db47
                                 at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:484
    12:     0x56451152135c - std::sys_common::backtrace::__rust_end_short_backtrace::h3bb85654c20113ca
                                 at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:153
    13:     0x564511523209 - rust_begin_unwind
                                 at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483
    14:     0x5645115231bb - std::panicking::begin_panic_fmt::hf0503558fbe5b251
                                 at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:437
    15:     0x5645115089e7 - build_script_build::run::h636e996b8adec085
                                 at /root/cncli/build.rs:46
    16:     0x56451150ab08 - build_script_build::main::hef09fca0a04a491e
                                 at /root/cncli/build.rs:33
    17:     0x564511504cab - core::ops::function::FnOnce::call_once::h332dcbb573992bc7
                                 at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/ops/function.rs:227
    18:     0x56451150a2de - std::sys_common::backtrace::__rust_begin_short_backtrace::h96bc3ecb13fdaa1a
                                 at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:137
    19:     0x56451150bda1 - std::rt::lang_start::{{closure}}::ha5cff8156b6388f1
                                 at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/rt.rs:66
    20:     0x564511523ac7 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::he179d32a5d10d957
                                 at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/ops/function.rs:259
    21:     0x564511523ac7 - std::panicking::try::do_call::hcb3d5e7be089b2b4
                                 at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:381
    22:     0x564511523ac7 - std::panicking::try::h7ac93b0cd56fb701
                                 at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:345
    23:     0x564511523ac7 - std::panic::catch_unwind::h7b40e396c93a4fcd
                                 at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panic.rs:382
    24:     0x564511523ac7 - std::rt::lang_start_internal::h142b9cc66267fea1
                                 at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/rt.rs:51
    25:     0x56451150bd77 - std::rt::lang_start::h21020496117b9023
                                 at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/rt.rs:65
    26:     0x56451150ab8a - main
    27:     0x7f5efa8f20b3 - __libc_start_main
    28:     0x56451150409e - _start
    29:                0x0 - <unknown>

```

**Comment by AndrewWestberg** [comment]
@amani1104 , I believe you were able to resolve this. Can you post a quick summary of what the issue is and then close this out? We want to give some guidance for the next person that comes across this issue.

**Comment by amani1104** [comment]
Yes, I could identify the issue that caused the build to fail. 

The hint was in: 

`configure: error: cannot run /bin/bash build-aux/config.sub`

config.sub and config.guess are downloaded during the compilation of libsodium, as specified in the autogen.sh file in the cncli/libsodium folder in lines 42-48: 

```
 42   curl -sSL -o config.guess \
 43     'https://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.guess;hb=HEAD' &&
 44     mv -f config.guess build-aux/config.guess
 45 
 46   curl -sSL -o config.sub \
 47     'https://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.sub;hb=HEAD' &&
 48     mv -f config.sub build-aux/config.sub

```
I checked the content of the files, which were: 

```
<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.4.6 (Trisquel GNU/Linux)</center>
</body>
</html>
```

This pointed to an issue on the server, from where the script tried to download the files from. 

I manually entered the curl commands above and checked the contents of the files, which both had the "Bad Gateway" error message.

The server issue had been fixed after a while, as compiling cncli worked after an hour or so with both config.sub and config.guess having had real content. 

So it turned out that error was caused by an error of a third party and not by a bug in cncli.
