### ISSUE TITLE
Panic when unwrapping version number

### ISSUE THREAD

**Issue by regiskuckaertz** [AndrewWestberg/cncli#22]
Hello 👋 First off, thank you for this nifty tool! I just installed version 1.0.1 and ran into an issue when trying to launch the `sendtip` command via systemd:
```
Jan 31 16:23:49 ip-172-31-14-76.eu-west-1.compute.internal cncli-sendtip[14245]: thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/nodeclient/pooltool.rs:70:135
Jan 31 16:23:49 ip-172-31-14-76.eu-west-1.compute.internal cncli-sendtip[14245]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Jan 31 16:23:49 ip-172-31-14-76.eu-west-1.compute.internal systemd[1]: cncli-sendtip.service: main process exited, code=exited, status=1/FAILURE
Jan 31 16:23:49 ip-172-31-14-76.eu-west-1.compute.internal systemd[1]: Unit cncli-sendtip.service entered failed state.
Jan 31 16:23:49 ip-172-31-14-76.eu-west-1.compute.internal systemd[1]: cncli-sendtip.service failed.
```

It works well when I run it on the CLI though, so I'm wondering whether there is something going on with how STDIO is handled with systemd processes. Any idea?

**Comment by AndrewWestberg** [comment]
@regiskuckaertz Can you let me know what the output of your

```
cardano-node --version
```

shows?

**Comment by regiskuckaertz** [comment]
Sure thing:
```
cardano-node 1.25.1 - linux-x86_64 - ghc-8.10
git rev 9a7331cce5e8bc0ea9c6bfa1c28773f4c5a7000f
```

**Comment by regiskuckaertz** [comment]
When run from the command line:
```
 2021-02-01T08:05:07.995Z WARN  cardano_ouroboros_network::protocols::transaction > TxSubmissionProtocol::State::Done
 2021-02-01T08:05:08.070Z WARN  cardano_ouroboros_network::protocols::chainsync   > rollback to slot: 4492799
 2021-02-01T08:05:08.075Z WARN  cardano_ouroboros_network::protocols::chainsync   > rollback to slot: 20600383
 2021-02-01T08:05:44.618Z INFO  cncli::nodeclient::pooltool                       > Checking cardano-node version: 1.25.1:9a733
 2021-02-01T08:05:45.248Z INFO  cncli::nodeclient::pooltool                       > Pooltool (BROS0, 69ebbe96): (5284751, 6ae3e891fb7c7190), json: {"success":true,"message":null}
```

**Comment by TrevorBenson** [comment]
Not trying to pollute the thread, but I've also received a panics with an unwrap(). 

- I've containerized cncli instead of using service units. 
- I had ptsendtip running for around 1 week when this happened.

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ErrorImpl { code: TrailingData, offset: 3 }', /root/.cargo/git/checkouts/rust-cardano-ouroboros-network-b5c2c96931e555ed/0a306c9/src/protocols/chainsync.rs:239:59
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Version:** cncli 1.0.2

**Comment by AndrewWestberg** [comment]
Should give a better error message in the latest version.

Also, @TrevorBenson , your issue was due to the node pipelining multiple cbor messages to us which is why it says "trailing data". This has also been resolved in the latest version.
