### ISSUE TITLE
Add support for Alonzo Purple

### ISSUE THREAD

**Issue by renesecur** [AndrewWestberg/cncli#90]
The shelley genesis for the Alonzo Purple network is currently not known causing a panic in sync mode

**Comment by TommieGoldhammer** [comment]
Here is a detailed error message. I hope this helps:

[...]
 2021-08-21T07:17:18.461Z WARN  cardano_ouroboros_network::protocols::chainsync > invalid cbor! code: 344
 2021-08-21T07:17:18.461Z WARN  cardano_ouroboros_network::protocols::chainsync > Probably a byron block. skipping...
 2021-08-21T07:17:18.461Z WARN  cardano_ouroboros_network::protocols::chainsync > invalid cbor! code: 344
 2021-08-21T07:17:18.461Z WARN  cardano_ouroboros_network::protocols::chainsync > Probably a byron block. skipping...
 2021-08-21T07:17:18.462Z INFO  cardano_ouroboros_network::protocols::chainsync > block 361 of 2149, 16.80% synced
 2021-08-21T07:17:19.186Z INFO  cardano_ouroboros_network::protocols::chainsync > block 2149 of 2149, 100.00% synced
thread 'main' panicked at 'Unknown genesis hash for network_magic 8', src/nodeclient/sqlite.rs:225:33
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
LeaderLog - POOLID 6a[...]45
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidColumnType(0, "MAX(slot_number)", Null)', src/nodeclient/leaderlog.rs:382:68
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by AndrewWestberg** [comment]
@TommieGoldhammer Make sure to install the latest version for Alonzo support.

**Comment by TommieGoldhammer** [comment]
@AndrewWestberg Thanks, the 3.1.5 version works fine now.
